//
// Created by Арсений Плахотнюк on 15.06.2024.
//

#ifndef CONTROLALGORITHMS_FIRSTORDERSLIDINGMODECONTROLWITHTIMEDELAY_HPP
#define CONTROLALGORITHMS_FIRSTORDERSLIDINGMODECONTROLWITHTIMEDELAY_HPP
namespace ControlAlgorithms::Controllers::FirstOrderSlidingModeWithTimeDelay{

}

#endif //CONTROLALGORITHMS_FIRSTORDERSLIDINGMODECONTROLWITHTIMEDELAY_HPP
